#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2023 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    # colorscheme = "desert"
    # colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # guifont = 'Sauce Code Pro Bold Italic Nerd Font Complete:h11'
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    # inactive windows
    statusline_iseparator = "nil"
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    enable_tabline_ft_icon = true
    enable_cursorline = true
    # 0: 1 ➛ ➊
    buffer_index_type = 0
    enable_statusline_tag = true
    # enable_powerline_fonts = true
    default_indent = 4

# Colorscheme
# https://spacevim.org/layers/colorscheme/
[[layers]]
  name = 'colorscheme'
  random_theme = true
  frequency = 'weekly'

# 
[[layers]]
  name = 'core#statusline'
  major_mode_cache = false
 
# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30
  
# Enable Fuzzy finder
# https://spacevim.org/documentation/#fuzzy-finder
[[layers]]
  name = 'denite'

# Enable Git integration
[[layers]]
  name = 'git'
[[layers]]
  name = 'VersionControl'

# Use Vim as a C/C++IDE
# https://spacevim.org/use-vim-as-a-c-cpp-ide/
[[layers]]
  name = 'lang#c'
  enable_clang_syntax_highlight = true


# Use Vim as a Python IDE
# https://spacevim.org/use-vim-as-a-python-ide/
[[layers]]
  name = 'lang#python'
  python_interpreter = '/usr/bin/python3'
  format_on_save = false
